export const POKEBALL_IMAGE_MAP: Record<string, string> = {
  pokeball:
    'https://raw.githubusercontent.com/parthenonlab/assets/main/pokeballs/poke-ball.png',
  greatball:
    'https://raw.githubusercontent.com/parthenonlab/assets/main/pokeballs/great-ball.png',
  ultraball:
    'https://raw.githubusercontent.com/parthenonlab/assets/main/pokeballs/ultra-ball.png',
  masterball:
    'https://raw.githubusercontent.com/parthenonlab/assets/main/pokeballs/master-ball.png',
};

export const POKEMON_TYPE_IMAGE_MAP: Record<string, string> = {
  normal: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/normal.png',
  fire: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/fire.png',
  water: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/water.png',
  electric: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/electric.png',
  grass: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/grass.png',
  ice: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/ice.png',
  fighting: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/fighting.png',
  poison: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/poison.png',
  ground: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/ground.png',
  flying: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/flying.png',
  psychic: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/psychic.png',
  bug: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/bug.png',
  rock: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/rock.png',
  ghost: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/ghost.png',
  dragon: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/dragon.png',
  steel: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/steel.png',
  fairy: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/fairy.png',
  dark: 'https://raw.githubusercontent.com/parthenonlab/assets/main/types/dark.png',
};

export const POKEMON_NAME_MAP: Record<string, string> = {
  'nidoran-f': 'Nidoran ♀',
  'nidoran-m': 'Nidoran ♂',
  'mr-mime': 'Mr. Mime',
  farfetchd: "Farfetch'd",
};

export const POKEMON_TYPE_MAP: Record<string, string[]> = {
  bulbasaur: ['grass', 'poison'],
  ivysaur: ['grass', 'poison'],
  venusaur: ['grass', 'poison'],
  charmander: ['fire'],
  charmeleon: ['fire'],
  charizard: ['fire', 'flying'],
  squirtle: ['water'],
  wartortle: ['water'],
  blastoise: ['water'],
  caterpie: ['bug'],
  metapod: ['bug'],
  butterfree: ['bug', 'flying'],
  weedle: ['bug', 'poison'],
  kakuna: ['bug', 'poison'],
  beedrill: ['bug', 'poison'],
  pidgey: ['normal', 'flying'],
  pidgeotto: ['normal', 'flying'],
  pidgeot: ['normal', 'flying'],
  rattata: ['normal'],
  raticate: ['normal'],
  spearow: ['normal', 'flying'],
  fearow: ['normal', 'flying'],
  ekans: ['poison'],
  arbok: ['poison'],
  pikachu: ['electric'],
  raichu: ['electric'],
  sandshrew: ['ground'],
  sandslash: ['ground'],
  'nidoran-f': ['poison'],
  nidorina: ['poison'],
  nidoqueen: ['poison', 'ground'],
  'nidoran-m': ['poison'],
  nidorino: ['poison'],
  nidoking: ['poison', 'ground'],
  clefairy: ['fairy'],
  clefable: ['fairy'],
  vulpix: ['fire'],
  ninetales: ['fire'],
  jigglypuff: ['normal', 'fairy'],
  wigglytuff: ['normal', 'fairy'],
  zubat: ['poison', 'flying'],
  golbat: ['poison', 'flying'],
  oddish: ['grass', 'poison'],
  gloom: ['grass', 'poison'],
  vileplume: ['grass', 'poison'],
  paras: ['bug', 'grass'],
  parasect: ['bug', 'grass'],
  venonat: ['bug', 'poison'],
  venomoth: ['bug', 'poison'],
  diglett: ['ground'],
  dugtrio: ['ground'],
  meowth: ['normal'],
  persian: ['normal'],
  psyduck: ['water'],
  golduck: ['water'],
  mankey: ['fighting'],
  primeape: ['fighting'],
  growlithe: ['fire'],
  arcanine: ['fire'],
  poliwag: ['water'],
  poliwhirl: ['water'],
  poliwrath: ['water', 'fighting'],
  abra: ['psychic'],
  kadabra: ['psychic'],
  alakazam: ['psychic'],
  machop: ['fighting'],
  machoke: ['fighting'],
  machamp: ['fighting'],
  bellsprout: ['grass', 'poison'],
  weepinbell: ['grass', 'poison'],
  victreebel: ['grass', 'poison'],
  tentacool: ['water', 'poison'],
  tentacruel: ['water', 'poison'],
  geodude: ['rock', 'ground'],
  graveler: ['rock', 'ground'],
  golem: ['rock', 'ground'],
  ponyta: ['fire'],
  rapidash: ['fire'],
  slowpoke: ['water', 'psychic'],
  slowbro: ['water', 'psychic'],
  magnemite: ['electric', 'steel'],
  magneton: ['electric', 'steel'],
  farfetchd: ['normal', 'flying'],
  doduo: ['normal', 'flying'],
  dodrio: ['normal', 'flying'],
  seel: ['water'],
  dewgong: ['water', 'ice'],
  grimer: ['poison'],
  muk: ['poison'],
  shellder: ['water'],
  cloyster: ['water', 'ice'],
  gastly: ['ghost', 'poison'],
  haunter: ['ghost', 'poison'],
  gengar: ['ghost', 'poison'],
  onix: ['rock', 'ground'],
  drowzee: ['psychic'],
  hypno: ['psychic'],
  krabby: ['water'],
  kingler: ['water'],
  voltorb: ['electric'],
  electrode: ['electric'],
  exeggcute: ['grass', 'psychic'],
  exeggutor: ['grass', 'psychic'],
  cubone: ['ground'],
  marowak: ['ground'],
  hitmonlee: ['fighting'],
  hitmonchan: ['fighting'],
  lickitung: ['normal'],
  koffing: ['poison'],
  weezing: ['poison'],
  rhyhorn: ['ground', 'rock'],
  rhydon: ['ground', 'rock'],
  chansey: ['normal'],
  tangela: ['grass'],
  kangaskhan: ['normal'],
  horsea: ['water'],
  seadra: ['water'],
  goldeen: ['water'],
  seaking: ['water'],
  staryu: ['water'],
  starmie: ['water', 'psychic'],
  'mr-mime': ['psychic', 'fairy'],
  scyther: ['bug', 'flying'],
  jynx: ['ice', 'psychic'],
  electabuzz: ['electric'],
  magmar: ['fire'],
  pinsir: ['bug'],
  tauros: ['normal'],
  magikarp: ['water'],
  gyarados: ['water', 'flying'],
  lapras: ['water', 'ice'],
  ditto: ['normal'],
  eevee: ['normal'],
  vaporeon: ['water'],
  jolteon: ['electric'],
  flareon: ['fire'],
  porygon: ['normal'],
  omanyte: ['rock', 'water'],
  omastar: ['rock', 'water'],
  kabuto: ['rock', 'water'],
  kabutops: ['rock', 'water'],
  aerodactyl: ['rock', 'flying'],
  snorlax: ['normal'],
  articuno: ['ice', 'flying'],
  zapdos: ['electric', 'flying'],
  moltres: ['fire', 'flying'],
  dratini: ['dragon'],
  dragonair: ['dragon'],
  dragonite: ['dragon', 'flying'],
  mewtwo: ['psychic'],
  mew: ['psychic'],
};
